const books = [
    { id: 1, title: "The Great Gatsby", price: 10.99, link: "https://example.com/gatsby.jpg" },
    { id: 2, title: "1984", price: 8.99, link: "https://example.com/1984.jpg" },
    { id: 3, title: "To Kill a Mockingbird", price: 12.99, link: "https://example.com/mockingbird.jpg" },
    { id: 4, title: "Pride and Prejudice", price: 9.99, link: "https://example.com/pride.jpg" },
    { id: 5, title: "The Catcher in the Rye", price: 10.99, link: "https://example.com/catcher.jpg" },
    { id: 6, title: "The Lord of the Rings", price: 15.99, link: "https://example.com/lordoftherings.jpg" },
    { id: 7, title: "The Hobbit", price: 12.99, link: "https://example.com/hobbit.jpg" },
    { id: 8, title: "Fahrenheit 451", price: 9.99, link: "https://example.com/fahrenheit.jpg" },
    { id: 9, title: "Brave New World", price: 11.99, link: "https://example.com/brave.jpg" },
    { id: 10, title: "The Picture of Dorian Gray", price: 10.99, link: "https://example.com/dorian.jpg" },
    { id: 11, title: "Moby Dick", price: 14.99, link: "https://example.com/mobydick.jpg" },
    { id: 12, title: "War and Peace", price: 19.99, link: "https://example.com/warandpeace.jpg" },
    { id: 13, title: "Crime and Punishment", price: 13.99, link: "https://example.com/crime.jpg" },
    { id: 14, title: "The Odyssey", price: 11.99, link: "https://example.com/odyssey.jpg" },
    { id: 15, title: "The Brothers Karamazov", price: 15.99, link: "https://example.com/brothers.jpg" },
    { id: 16, title: "The Grapes of Wrath", price: 12.99, link: "https://example.com/grapes.jpg" },
    { id: 17, title: "Jane Eyre", price: 10.99, link: "https://example.com/janeeyre.jpg" },
    { id: 18, title: "Wuthering Heights", price: 11.99, link: "https://example.com/wuthering.jpg" },
    { id: 19, title: "The Bell Jar", price: 9.99, link: "https://example.com/belljar.jpg" },
    { id: 20, title: "The Road", price: 12.99, link: "https://example.com/road.jpg" }
];